namespace Eshop.Share.Enum
{
    public enum GlobalResourceEnums
    {
        Success = 0,
        ServerError = 1,
        LicenseError = 2,
        BadRequest = 3,
        NotFound = 4,
        IllegalOperation = 5,
        Exception = 6,
        NameAlreadyExist = 7,
        CodeAlreadyExist = 8,
        SearchedItemsAlreadyExist = 9,
        CompoundKeysAlreadyExist = 10,
        NameIsRequired = 11,
        CodeIsRequired = 12,
        NodeHaveChild = 13,
        UnauthorizedAccessToAction = 14,
        ChooseFoodTypeIsRequired = 15,
        AddComplete = 16,
        EditComplete = 17,
        BeforeDeleteOperationNotComplate = 18,
        BeforeEditOperationNotComplate = 19,
        BeforeAddOperationNotComplate = 20,
        AfterEditOperationNotComplate = 21,
        AfterAddOperationNotComplate = 22,
        DeleteComplete = 23,
        OperationError = 24,
        Month1E = 25,
        Month2E = 26,
        Month3E = 27,
        Month4E = 28,
        Month5E = 29,
        Month6E = 30,
        Month7E = 31,
        Month8E = 32,
        Month9E = 33,
        Month10E = 34,
        Month11E = 35,
        Month12E = 36,
        Day1E = 37,
        Day2E = 38,
        Day3E = 39,
        Day4E = 40,
        Day5E = 41,
        Day6E = 42,
        Day7E = 43,
        Month1NE = 44,
        Month2NE = 45,
        Month3NE = 46,
        Month4NE = 47,
        Month5NE = 48,
        Month6NE = 49,
        Month7NE = 50,
        Month8NE = 51,
        Month9NE = 52,
        Month10NE = 53,
        Month11NE = 54,
        Month12NE = 55,
        Day1NE = 56,
        Day2NE = 57,
        Day3NE = 58,
        Day4NE = 59,
        Day5NE = 60,
        Day6NE = 61,
        Day7NE = 62,
        IdIsNull = 63,
        ThereIsaDefaultValue = 64,
        BeforeDeleteRangeOperationNotComplate = 65,
        BeforeAddRangeOperationNotComplate = 66,
        UserNameOrPasswordIsIncorrect = 67,
        RoleNotExist = 68,
        CantChangeStep = 69,
        LockOrder = 70,
        DamageAlreadyRegistered = 71,
        ChoseDamagedColors = 72,
        CantDeleteGroupCausesDamage = 73,
        CantDeletePersonCausesDamage = 74,
        CantDeleteDamageReason = 75,
        ChooseOrganizationUnitsIsRequired = 76,
        NotAllPlateInCuttingStep = 77,
        CantChangeStepHasDamage = 78,
        UserNotActive = 79,
        CantDeleteReportFilterCategory = 80,
        OrderMustHaveDesigner = 81,
        RemoteWorkNotPossible = 82
    }

    public enum ResultType
    {
        Success = 0,
        Info = 1,
        Warning = 2,
        Error = 3,
    }

    public enum ResultStatusTypeEnum
    {
        ServerError = 0,
        UIError = 1
    }

}